### ISSUE TITLE
Kann Erweiterung nicht deinstallieren

### ISSUE THREAD

**Issue by akroii** [heimrichhannot/contao-components#1]
Ich habe ein Contao 4.4.9 / Managed Edition.

Sobald ich im Manager versuche diese zu deinstallieren erscheint:
```
Loading composer repositories with package information
Updating dependencies
--------------------------------------------------------
Exception occured: The contents of https://packagist.org/p/provider-latest%240cbfb40ab72a881d21b70f78286d39cd72e3b0eb8704c13e79dc49624e549973.json do not match its signature. This could indicate a man-in-the-middle attack. Try running composer again and report this if you think it is a mistake.
#0 phar:///Applications/MAMP/htdocs/schmdit/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Composer/AbstractComposerCommandTask.php(166): Tenside\Core\Task\Composer\AbstractComposerCommandTask->executeCommand(Object(Tenside\Core\Task\Composer\WrappedCommand\RemoveCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Tenside\Core\Task\TaskOutput))
#1 phar:///Applications/MAMP/htdocs/schmdit/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Task.php(173): Tenside\Core\Task\Composer\AbstractComposerCommandTask->doPerform()
#2 phar:///Applications/MAMP/htdocs/schmdit/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Runner.php(89): Tenside\Core\Task\Task->perform('/Applications/M...')
#3 phar:///Applications/MAMP/htdocs/schmdit/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(82): Tenside\Core\Task\Runner->run('/Applications/M...')
#4 phar:///Applications/MAMP/htdocs/schmdit/web/contao-manager.phar.php/vendor/symfony/console/Command/Command.php(240): Tenside\CoreBundle\Command\RunTaskCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 phar:///Applications/MAMP/htdocs/schmdit/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(61): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 phar:///Applications/MAMP/htdocs/schmdit/web/contao-manager.phar.php/vendor/symfony/console/Application.php(875): Tenside\CoreBundle\Command\RunTaskCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 phar:///Applications/MAMP/htdocs/schmdit/web/contao-manager.phar.php/vendor/symfony/console/Application.php(215): Symfony\Component\Console\Application->doRunCommand(Object(Tenside\CoreBundle\Command\RunTaskCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 phar:///Applications/MAMP/htdocs/schmdit/web/contao-manager.phar.php/api/ApiApplication.php(71): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///Applications/MAMP/htdocs/schmdit/web/contao-manager.phar.php/vendor/symfony/console/Application.php(122): Contao\ManagerApi\ApiApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar:///Applications/MAMP/htdocs/schmdit/web/contao-manager.phar.php/api/console(83): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /Applications/MAMP/htdocs/schmdit/web/contao-manager.phar.php(55): require('phar:///Applica...')
#12 {main}
Chained exception: The contents of https://packagist.org/p/provider-latest%240cbfb40ab72a881d21b70f78286d39cd72e3b0eb8704c13e79dc49624e549973.json do not match its signature. This could indicate a man-in-the-middle attack. Try running composer again and report this if you think it is a mistake.
#0 phar:///Applications/MAMP/htdocs/schmdit/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/Repository/ComposerRepository.php(576): Composer\Repository\ComposerRepository->fetchFile('https://packagi...', 'p/provider-late...', '0cbfb40ab72a881...')
#1 phar:///Applications/MAMP/htdocs/schmdit/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/Repository/ComposerRepository.php(296): Composer\Repository\ComposerRepository->loadProviderListings(Array)
#2 phar:///Applications/MAMP/htdocs/schmdit/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/DependencyResolver/Pool.php(204): Composer\Repository\ComposerRepository->whatProvides(Object(Composer\DependencyResolver\Pool), 'contao-componen...', false)
#3 phar:///Applications/MAMP/htdocs/schmdit/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/DependencyResolver/Pool.php(193): Composer\DependencyResolver\Pool->computeWhatProvides('contao-componen...', Object(Composer\Semver\Constraint\MultiConstraint), true, false)
#4 phar:///Applications/MAMP/htdocs/schmdit/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/DependencyResolver/RuleSetGenerator.php(161): Composer\DependencyResolver\Pool->whatProvides('contao-componen...', Object(Composer\Semver\Constraint\MultiConstraint), true)
#5 phar:///Applications/MAMP/htdocs/schmdit/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/DependencyResolver/RuleSetGenerator.php(322): Composer\DependencyResolver\RuleSetGenerator->whitelistFromPackage(Object(Composer\Package\CompletePackage))
#6 phar:///Applications/MAMP/htdocs/schmdit/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/DependencyResolver/Solver.php(214): Composer\DependencyResolver\RuleSetGenerator->getRulesFor(Array, Array, false)
#7 phar:///Applications/MAMP/htdocs/schmdit/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/Installer.php(472): Composer\DependencyResolver\Solver->solve(Object(Composer\DependencyResolver\Request), false)
#8 phar:///Applications/MAMP/htdocs/schmdit/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/Installer.php(226): Composer\Installer->doInstall(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\Repository\CompositeRepository), Object(Composer\Repository\PlatformRepository), Array)
#9 phar:///Applications/MAMP/htdocs/schmdit/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/Command/RemoveCommand.php(139): Composer\Installer->run()
#10 phar:///Applications/MAMP/htdocs/schmdit/web/contao-manager.phar.php/vendor/symfony/console/Command/Command.php(240): Composer\Command\RemoveCommand->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Tenside\Core\Task\TaskOutput))
#11 phar:///Applications/MAMP/htdocs/schmdit/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Composer/AbstractComposerCommandTask.php(147): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Tenside\Core\Task\TaskOutput))
#12 phar:///Applications/MAMP/htdocs/schmdit/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Composer/AbstractComposerCommandTask.php(166): Tenside\Core\Task\Composer\AbstractComposerCommandTask->executeCommand(Object(Tenside\Core\Task\Composer\WrappedCommand\RemoveCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Tenside\Core\Task\TaskOutput))
#13 phar:///Applications/MAMP/htdocs/schmdit/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Task.php(173): Tenside\Core\Task\Composer\AbstractComposerCommandTask->doPerform()
#14 phar:///Applications/MAMP/htdocs/schmdit/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Runner.php(89): Tenside\Core\Task\Task->perform('/Applications/M...')
#15 phar:///Applications/MAMP/htdocs/schmdit/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(82): Tenside\Core\Task\Runner->run('/Applications/M...')
#16 phar:///Applications/MAMP/htdocs/schmdit/web/contao-manager.phar.php/vendor/symfony/console/Command/Command.php(240): Tenside\CoreBundle\Command\RunTaskCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 phar:///Applications/MAMP/htdocs/schmdit/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(61): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 phar:///Applications/MAMP/htdocs/schmdit/web/contao-manager.phar.php/vendor/symfony/console/Application.php(875): Tenside\CoreBundle\Command\RunTaskCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 phar:///Applications/MAMP/htdocs/schmdit/web/contao-manager.phar.php/vendor/symfony/console/Application.php(215): Symfony\Component\Console\Application->doRunCommand(Object(Tenside\CoreBundle\Command\RunTaskCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 phar:///Applications/MAMP/htdocs/schmdit/web/contao-manager.phar.php/api/ApiApplication.php(71): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 phar:///Applications/MAMP/htdocs/schmdit/web/contao-manager.phar.php/vendor/symfony/console/Application.php(122): Contao\ManagerApi\ApiApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 phar:///Applications/MAMP/htdocs/schmdit/web/contao-manager.phar.php/api/console(83): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /Applications/MAMP/htdocs/schmdit/web/contao-manager.phar.php(55): require('phar:///Applica...')
#24 {main}
--------------------------------------------------------


Process terminated with exit code 1
Reason: General error
```

**Comment by fatcrobat** [comment]
Packagist hatte gestern Serverprobleme. Versuch es erneut, der Fehler liegt hier nicht an unserer Erweiterung.

**Comment by akroii** [comment]
Seltsam ist, dass contao-components nicht im Manager erscheint, in der composer.lock aber ganz normal aufgeführt ist.
